package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.UserValidation;
import org.strasa.middleware.model.UserValidationExample;

public interface UserValidationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @SelectProvider(type=UserValidationSqlProvider.class, method="countByExample")
    int countByExample(UserValidationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @DeleteProvider(type=UserValidationSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserValidationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @Delete({
        "delete from uservalidation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @Insert({
        "insert into uservalidation (userID, confirmationcode, ",
        "date_created)",
        "values (#{userid,jdbcType=INTEGER}, #{confirmationcode,jdbcType=VARCHAR}, ",
        "#{dateCreated,jdbcType=DATE})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(UserValidation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @InsertProvider(type=UserValidationSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(UserValidation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @SelectProvider(type=UserValidationSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userID", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="confirmationcode", property="confirmationcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="date_created", property="dateCreated", jdbcType=JdbcType.DATE)
    })
    List<UserValidation> selectByExample(UserValidationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @Select({
        "select",
        "id, userID, confirmationcode, date_created",
        "from uservalidation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userID", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="confirmationcode", property="confirmationcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="date_created", property="dateCreated", jdbcType=JdbcType.DATE)
    })
    UserValidation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @UpdateProvider(type=UserValidationSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserValidation record, @Param("example") UserValidationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @UpdateProvider(type=UserValidationSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserValidation record, @Param("example") UserValidationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @UpdateProvider(type=UserValidationSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserValidation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uservalidation
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    @Update({
        "update uservalidation",
        "set userID = #{userid,jdbcType=INTEGER},",
          "confirmationcode = #{confirmationcode,jdbcType=VARCHAR},",
          "date_created = #{dateCreated,jdbcType=DATE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserValidation record);
}