/*
SQLyog Community Edition- MySQL GUI v6.03
Host - 5.5.23-log : Database - strasa
*********************************************************************
Server version : 5.5.23-log
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*Table structure for table `studydatacolumn` */

DROP TABLE IF EXISTS `studydatacolumn`;

CREATE TABLE `studydatacolumn` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `studyid` int(10) DEFAULT NULL,
  `columnheader` varchar(20) DEFAULT NULL,
  `datatype` enum('dd','rd') DEFAULT 'rd',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

/*Data for the table `studydatacolumn` */

insert  into `studydatacolumn`(`id`,`studyid`,`columnheader`,`datatype`) values (1,1,'GName','rd');
insert  into `studydatacolumn`(`id`,`studyid`,`columnheader`,`datatype`) values (2,1,'Source','rd');
insert  into `studydatacolumn`(`id`,`studyid`,`columnheader`,`datatype`) values (3,1,'Rep','rd');
insert  into `studydatacolumn`(`id`,`studyid`,`columnheader`,`datatype`) values (7,1,'Season','rd');
insert  into `studydatacolumn`(`id`,`studyid`,`columnheader`,`datatype`) values (8,1,'Year','rd');
insert  into `studydatacolumn`(`id`,`studyid`,`columnheader`,`datatype`) values (9,1,'Yld','rd');
insert  into `studydatacolumn`(`id`,`studyid`,`columnheader`,`datatype`) values (10,1,'DF','rd');

/*Table structure for table `studyrawdata` */

DROP TABLE IF EXISTS `studyrawdata`;

CREATE TABLE `studyrawdata` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `studyid` int(10) DEFAULT NULL,
  `datarow` int(10) DEFAULT NULL,
  `datacolumn` varchar(20) DEFAULT NULL,
  `datavalue` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11706 DEFAULT CHARSET=latin1;

/*Data for the table `studyrawdata` */

insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7897,1,1,'Gname','IR8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7898,1,2,'Gname','IR22');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7899,1,3,'Gname','IR36');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7900,1,4,'Gname','IR64');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7901,1,5,'Gname','IR72');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7902,1,6,'Gname','RC222');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7903,1,7,'Gname','IR46sub1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7904,1,8,'Gname','IR8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7905,1,9,'Gname','IR22');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7906,1,10,'Gname','IR36');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7907,1,11,'Gname','IR64');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7908,1,12,'Gname','IR72');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7909,1,13,'Gname','RC222');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7910,1,14,'Gname','IR46sub1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7911,1,15,'Gname','IR8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7912,1,16,'Gname','IR22');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7913,1,17,'Gname','IR36');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7914,1,18,'Gname','IR64');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7915,1,19,'Gname','IR72');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7916,1,20,'Gname','RC222');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7917,1,21,'Gname','IR46sub1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7918,1,22,'Gname','IR8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7919,1,23,'Gname','IR22');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7920,1,24,'Gname','IR36');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7921,1,25,'Gname','IR64');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7922,1,26,'Gname','IR72');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7923,1,27,'Gname','PR01');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7924,1,28,'Gname','PR02');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7925,1,29,'Gname','PR03');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7926,1,30,'Gname','PR04');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7927,1,31,'Gname','IR8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7928,1,32,'Gname','IR22');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7929,1,33,'Gname','IR36');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7930,1,34,'Gname','IR64');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7931,1,35,'Gname','IR72');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7932,1,36,'Gname','PR01');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7933,1,37,'Gname','PR02');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7934,1,38,'Gname','PR03');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7935,1,39,'Gname','PR04');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7936,1,40,'Gname','IR22');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7937,1,41,'Gname','IR36');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7938,1,42,'Gname','IR64');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7939,1,43,'Gname','IR72');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7940,1,44,'Gname','PR01');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7941,1,45,'Gname','PR02');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7942,1,46,'Gname','PR03');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7943,1,47,'Gname','PR04');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7944,1,1,'Source','Source 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7945,1,2,'Source','Source 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7946,1,3,'Source','Source 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7947,1,4,'Source','Source 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7948,1,5,'Source','Source 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7949,1,6,'Source','Source 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7950,1,7,'Source','Source 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7951,1,8,'Source','Source 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7952,1,9,'Source','Source 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7953,1,10,'Source','Source 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7954,1,11,'Source','Source 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7955,1,12,'Source','Source 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7956,1,13,'Source','Source 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7957,1,14,'Source','Source 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7958,1,15,'Source','Source 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7959,1,16,'Source','Source 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7960,1,17,'Source','Source 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7961,1,18,'Source','Source 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7962,1,19,'Source','Source 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7963,1,20,'Source','Source 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7964,1,21,'Source','Source 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7965,1,22,'Source','Source 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7966,1,23,'Source','Source 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7967,1,24,'Source','Source 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7968,1,25,'Source','Source 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7969,1,26,'Source','Source 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7970,1,27,'Source','Source 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7971,1,28,'Source','Source 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7972,1,29,'Source','Source 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7973,1,30,'Source','Source 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7974,1,31,'Source','Source 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7975,1,32,'Source','Source 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7976,1,33,'Source','Source 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7977,1,34,'Source','Source 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7978,1,35,'Source','Source 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7979,1,36,'Source','Source 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7980,1,37,'Source','Source 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7981,1,38,'Source','Source 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7982,1,39,'Source','Source 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7983,1,40,'Source','Source 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7984,1,41,'Source','Source 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7985,1,42,'Source','Source 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7986,1,43,'Source','Source 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7987,1,44,'Source','Source 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7988,1,45,'Source','Source 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7989,1,46,'Source','Source 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7990,1,47,'Source','Source 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7991,1,1,'Female Parent','Female 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7992,1,2,'Female Parent','Female 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7993,1,3,'Female Parent','Female 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7994,1,4,'Female Parent','Female 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7995,1,5,'Female Parent','Female 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7996,1,6,'Female Parent','Female 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7997,1,7,'Female Parent','Female 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7998,1,8,'Female Parent','Female 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (7999,1,9,'Female Parent','Female 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8000,1,10,'Female Parent','Female 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8001,1,11,'Female Parent','Female 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8002,1,12,'Female Parent','Female 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8003,1,13,'Female Parent','Female 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8004,1,14,'Female Parent','Female 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8005,1,15,'Female Parent','Female 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8006,1,16,'Female Parent','Female 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8007,1,17,'Female Parent','Female 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8008,1,18,'Female Parent','Female 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8009,1,19,'Female Parent','Female 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8010,1,20,'Female Parent','Female 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8011,1,21,'Female Parent','Female 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8012,1,22,'Female Parent','Female 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8013,1,23,'Female Parent','Female 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8014,1,24,'Female Parent','Female 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8015,1,25,'Female Parent','Female 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8016,1,26,'Female Parent','Female 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8017,1,27,'Female Parent','Female 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8018,1,28,'Female Parent','Female 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8019,1,29,'Female Parent','Female 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8020,1,30,'Female Parent','Female 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8021,1,31,'Female Parent','Female 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8022,1,32,'Female Parent','Female 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8023,1,33,'Female Parent','Female 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8024,1,34,'Female Parent','Female 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8025,1,35,'Female Parent','Female 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8026,1,36,'Female Parent','Female 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8027,1,37,'Female Parent','Female 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8028,1,38,'Female Parent','Female 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8029,1,39,'Female Parent','Female 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8030,1,40,'Female Parent','Female 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8031,1,41,'Female Parent','Female 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8032,1,42,'Female Parent','Female 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8033,1,43,'Female Parent','Female 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8034,1,44,'Female Parent','Female 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8035,1,45,'Female Parent','Female 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8036,1,46,'Female Parent','Female 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8037,1,47,'Female Parent','Female 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8038,1,1,'Male Parent','Male 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8039,1,2,'Male Parent','Male 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8040,1,3,'Male Parent','Male 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8041,1,4,'Male Parent','Male 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8042,1,5,'Male Parent','Male 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8043,1,6,'Male Parent','Male 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8044,1,7,'Male Parent','Male 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8045,1,8,'Male Parent','Male 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8046,1,9,'Male Parent','Male 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8047,1,10,'Male Parent','Male 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8048,1,11,'Male Parent','Male 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8049,1,12,'Male Parent','Male 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8050,1,13,'Male Parent','Male 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8051,1,14,'Male Parent','Male 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8052,1,15,'Male Parent','Male 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8053,1,16,'Male Parent','Male 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8054,1,17,'Male Parent','Male 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8055,1,18,'Male Parent','Male 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8056,1,19,'Male Parent','Male 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8057,1,20,'Male Parent','Male 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8058,1,21,'Male Parent','Male 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8059,1,22,'Male Parent','Male 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8060,1,23,'Male Parent','Male 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8061,1,24,'Male Parent','Male 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8062,1,25,'Male Parent','Male 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8063,1,26,'Male Parent','Male 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8064,1,27,'Male Parent','Male 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8065,1,28,'Male Parent','Male 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8066,1,29,'Male Parent','Male 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8067,1,30,'Male Parent','Male 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8068,1,31,'Male Parent','Male 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8069,1,32,'Male Parent','Male 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8070,1,33,'Male Parent','Male 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8071,1,34,'Male Parent','Male 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8072,1,35,'Male Parent','Male 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8073,1,36,'Male Parent','Male 6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8074,1,37,'Male Parent','Male 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8075,1,38,'Male Parent','Male 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8076,1,39,'Male Parent','Male 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8077,1,40,'Male Parent','Male 1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8078,1,41,'Male Parent','Male 2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8079,1,42,'Male Parent','Male 3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8080,1,43,'Male Parent','Male 4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8081,1,44,'Male Parent','Male 5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8082,1,45,'Male Parent','Male 7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8083,1,46,'Male Parent','Male 8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8084,1,47,'Male Parent','Male 9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8085,1,1,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8086,1,2,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8087,1,3,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8088,1,4,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8089,1,5,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8090,1,6,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8091,1,7,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8092,1,8,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8093,1,9,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8094,1,10,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8095,1,11,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8096,1,12,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8097,1,13,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8098,1,14,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8099,1,15,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8100,1,16,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8101,1,17,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8102,1,18,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8103,1,19,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8104,1,20,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8105,1,21,'Location','Los Banos');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8106,1,22,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8107,1,23,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8108,1,24,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8109,1,25,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8110,1,26,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8111,1,27,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8112,1,28,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8113,1,29,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8114,1,30,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8115,1,31,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8116,1,32,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8117,1,33,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8118,1,34,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8119,1,35,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8120,1,36,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8121,1,37,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8122,1,38,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8123,1,39,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8124,1,40,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8125,1,41,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8126,1,42,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8127,1,43,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8128,1,44,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8129,1,45,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8130,1,46,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8131,1,47,'Location','Nueva Ecija');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8132,1,1,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8133,1,2,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8134,1,3,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8135,1,4,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8136,1,5,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8137,1,6,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8138,1,7,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8139,1,8,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8140,1,9,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8141,1,10,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8142,1,11,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8143,1,12,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8144,1,13,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8145,1,14,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8146,1,15,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8147,1,16,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8148,1,17,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8149,1,18,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8150,1,19,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8151,1,20,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8152,1,21,'Site','IRRI');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8153,1,22,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8154,1,23,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8155,1,24,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8156,1,25,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8157,1,26,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8158,1,27,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8159,1,28,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8160,1,29,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8161,1,30,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8162,1,31,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8163,1,32,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8164,1,33,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8165,1,34,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8166,1,35,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8167,1,36,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8168,1,37,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8169,1,38,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8170,1,39,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8171,1,40,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8172,1,41,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8173,1,42,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8174,1,43,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8175,1,44,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8176,1,45,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8177,1,46,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8178,1,47,'Site','PhilRice');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8179,1,1,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8180,1,2,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8181,1,3,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8182,1,4,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8183,1,5,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8184,1,6,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8185,1,7,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8186,1,8,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8187,1,9,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8188,1,10,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8189,1,11,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8190,1,12,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8191,1,13,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8192,1,14,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8193,1,15,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8194,1,16,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8195,1,17,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8196,1,18,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8197,1,19,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8198,1,20,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8199,1,21,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8200,1,22,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8201,1,23,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8202,1,24,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8203,1,25,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8204,1,26,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8205,1,27,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8206,1,28,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8207,1,29,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8208,1,30,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8209,1,31,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8210,1,32,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8211,1,33,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8212,1,34,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8213,1,35,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8214,1,36,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8215,1,37,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8216,1,38,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8217,1,39,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8218,1,40,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8219,1,41,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8220,1,42,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8221,1,43,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8222,1,44,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8223,1,45,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8224,1,46,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8225,1,47,'Year','2013');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8226,1,1,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8227,1,2,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8228,1,3,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8229,1,4,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8230,1,5,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8231,1,6,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8232,1,7,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8233,1,8,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8234,1,9,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8235,1,10,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8236,1,11,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8237,1,12,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8238,1,13,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8239,1,14,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8240,1,15,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8241,1,16,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8242,1,17,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8243,1,18,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8244,1,19,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8245,1,20,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8246,1,21,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8247,1,22,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8248,1,23,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8249,1,24,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8250,1,25,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8251,1,26,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8252,1,27,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8253,1,28,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8254,1,29,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8255,1,30,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8256,1,31,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8257,1,32,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8258,1,33,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8259,1,34,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8260,1,35,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8261,1,36,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8262,1,37,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8263,1,38,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8264,1,39,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8265,1,40,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8266,1,41,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8267,1,42,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8268,1,43,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8269,1,44,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8270,1,45,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8271,1,46,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8272,1,47,'Season','D');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8273,1,1,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8274,1,2,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8275,1,3,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8276,1,4,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8277,1,5,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8278,1,6,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8279,1,7,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8280,1,8,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8281,1,9,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8282,1,10,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8283,1,11,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8284,1,12,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8285,1,13,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8286,1,14,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8287,1,15,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8288,1,16,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8289,1,17,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8290,1,18,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8291,1,19,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8292,1,20,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8293,1,21,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8294,1,22,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8295,1,23,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8296,1,24,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8297,1,25,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8298,1,26,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8299,1,27,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8300,1,28,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8301,1,29,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8302,1,30,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8303,1,31,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8304,1,32,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8305,1,33,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8306,1,34,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8307,1,35,'Rep','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8308,1,36,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8309,1,37,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8310,1,38,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8311,1,39,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8312,1,40,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8313,1,41,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8314,1,42,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8315,1,43,'Rep','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8316,1,44,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8317,1,45,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8318,1,46,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8319,1,47,'Rep','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8320,1,1,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8321,1,2,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8322,1,3,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8323,1,4,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8324,1,5,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8325,1,6,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8326,1,7,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8327,1,8,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8328,1,9,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8329,1,10,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8330,1,11,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8331,1,12,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8332,1,13,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8333,1,14,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8334,1,15,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8335,1,16,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8336,1,17,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8337,1,18,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8338,1,19,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8339,1,20,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8340,1,21,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8341,1,22,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8342,1,23,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8343,1,24,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8344,1,25,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8345,1,26,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8346,1,27,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8347,1,28,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8348,1,29,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8349,1,30,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8350,1,31,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8351,1,32,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8352,1,33,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8353,1,34,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8354,1,35,'Block','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8355,1,36,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8356,1,37,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8357,1,38,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8358,1,39,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8359,1,40,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8360,1,41,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8361,1,42,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8362,1,43,'Block','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8363,1,44,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8364,1,45,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8365,1,46,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8366,1,47,'Block','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8367,1,1,'FieldRow','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8368,1,2,'FieldRow','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8369,1,3,'FieldRow','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8370,1,4,'FieldRow','4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8371,1,5,'FieldRow','5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8372,1,6,'FieldRow','6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8373,1,7,'FieldRow','7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8374,1,8,'FieldRow','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8375,1,9,'FieldRow','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8376,1,10,'FieldRow','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8377,1,11,'FieldRow','4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8378,1,12,'FieldRow','5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8379,1,13,'FieldRow','6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8380,1,14,'FieldRow','7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8381,1,15,'FieldRow','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8382,1,16,'FieldRow','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8383,1,17,'FieldRow','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8384,1,18,'FieldRow','4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8385,1,19,'FieldRow','5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8386,1,20,'FieldRow','6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8387,1,21,'FieldRow','7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8388,1,22,'FieldRow','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8389,1,23,'FieldRow','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8390,1,24,'FieldRow','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8391,1,25,'FieldRow','4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8392,1,26,'FieldRow','5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8393,1,27,'FieldRow','6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8394,1,28,'FieldRow','7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8395,1,29,'FieldRow','8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8396,1,30,'FieldRow','9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8397,1,31,'FieldRow','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8398,1,32,'FieldRow','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8399,1,33,'FieldRow','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8400,1,34,'FieldRow','4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8401,1,35,'FieldRow','5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8402,1,36,'FieldRow','6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8403,1,37,'FieldRow','7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8404,1,38,'FieldRow','8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8405,1,39,'FieldRow','9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8406,1,40,'FieldRow','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8407,1,41,'FieldRow','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8408,1,42,'FieldRow','4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8409,1,43,'FieldRow','5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8410,1,44,'FieldRow','6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8411,1,45,'FieldRow','7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8412,1,46,'FieldRow','8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8413,1,47,'FieldRow','9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8414,1,1,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8415,1,2,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8416,1,3,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8417,1,4,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8418,1,5,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8419,1,6,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8420,1,7,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8421,1,8,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8422,1,9,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8423,1,10,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8424,1,11,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8425,1,12,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8426,1,13,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8427,1,14,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8428,1,15,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8429,1,16,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8430,1,17,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8431,1,18,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8432,1,19,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8433,1,20,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8434,1,21,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8435,1,22,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8436,1,23,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8437,1,24,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8438,1,25,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8439,1,26,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8440,1,27,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8441,1,28,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8442,1,29,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8443,1,30,'FieldColmn','1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8444,1,31,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8445,1,32,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8446,1,33,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8447,1,34,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8448,1,35,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8449,1,36,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8450,1,37,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8451,1,38,'FieldColmn','2');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8452,1,39,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8453,1,40,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8454,1,41,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8455,1,42,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8456,1,43,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8457,1,44,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8458,1,45,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8459,1,46,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8460,1,47,'FieldColmn','3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8461,1,1,'PH','110');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8462,1,2,'PH','115');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8463,1,3,'PH','120');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8464,1,4,'PH','113');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8465,1,5,'PH','105');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8466,1,6,'PH','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8467,1,7,'PH','111');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8468,1,8,'PH','111');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8469,1,9,'PH','116');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8470,1,10,'PH','121');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8471,1,11,'PH','114');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8472,1,12,'PH','106');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8473,1,13,'PH','101');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8474,1,14,'PH','112');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8475,1,15,'PH','109');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8476,1,16,'PH','114');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8477,1,17,'PH','119');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8478,1,18,'PH','112');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8479,1,19,'PH','104');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8480,1,20,'PH','99');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8481,1,21,'PH','110');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8482,1,22,'PH','112');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8483,1,23,'PH','117');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8484,1,24,'PH','122');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8485,1,25,'PH','115');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8486,1,26,'PH','107');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8487,1,27,'PH','102');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8488,1,28,'PH','113');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8489,1,29,'PH','113');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8490,1,30,'PH','118');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8491,1,31,'PH','123');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8492,1,32,'PH','116');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8493,1,33,'PH','108');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8494,1,34,'PH','103');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8495,1,35,'PH','114');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8496,1,36,'PH','111');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8497,1,37,'PH','116');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8498,1,38,'PH','121');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8499,1,39,'PH','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8500,1,40,'PH','106');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8501,1,41,'PH','101');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8502,1,42,'PH','112');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8503,1,43,'PH','114');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8504,1,44,'PH','119');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8505,1,45,'PH','124');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8506,1,46,'PH','117');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8507,1,47,'PH','109');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8508,1,1,'DF','80');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8509,1,2,'DF','85');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8510,1,3,'DF','90');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8511,1,4,'DF','91');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8512,1,5,'DF','96');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8513,1,6,'DF','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8514,1,7,'DF','88');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8515,1,8,'DF','82');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8516,1,9,'DF','87');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8517,1,10,'DF','92');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8518,1,11,'DF','93');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8519,1,12,'DF','98');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8520,1,13,'DF','88');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8521,1,14,'DF','90');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8522,1,15,'DF','85');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8523,1,16,'DF','90');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8524,1,17,'DF','95');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8525,1,18,'DF','96');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8526,1,19,'DF','101');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8527,1,20,'DF','91');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8528,1,21,'DF','93');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8529,1,22,'DF','80.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8530,1,23,'DF','85.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8531,1,24,'DF','90.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8532,1,25,'DF','91.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8533,1,26,'DF','96.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8534,1,27,'DF','86.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8535,1,28,'DF','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8536,1,29,'DF','82.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8537,1,30,'DF','87.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8538,1,31,'DF','92.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8539,1,32,'DF','93.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8540,1,33,'DF','98.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8541,1,34,'DF','88.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8542,1,35,'DF','90.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8543,1,36,'DF','85.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8544,1,37,'DF','90.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8545,1,38,'DF','95.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8546,1,39,'DF','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8547,1,40,'DF','101.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8548,1,41,'DF','91.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8549,1,42,'DF','93.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8550,1,43,'DF','81');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8551,1,44,'DF','86');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8552,1,45,'DF','91');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8553,1,46,'DF','92');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8554,1,47,'DF','97');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8555,1,1,'Yld','5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8556,1,2,'Yld','5.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8557,1,3,'Yld','6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8558,1,4,'Yld','6.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8559,1,5,'Yld','7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8560,1,6,'Yld','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8561,1,7,'Yld','7.3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8562,1,8,'Yld','5.1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8563,1,9,'Yld','5.6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8564,1,10,'Yld','6.1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8565,1,11,'Yld','6.6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8566,1,12,'Yld','7.1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8567,1,13,'Yld','7.3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8568,1,14,'Yld','7.4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8569,1,15,'Yld','5.15');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8570,1,16,'Yld','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8571,1,17,'Yld','6.15');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8572,1,18,'Yld','6.65');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8573,1,19,'Yld','7.15');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8574,1,20,'Yld','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8575,1,21,'Yld','7.45');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8576,1,22,'Yld','5.3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8577,1,23,'Yld','5.8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8578,1,24,'Yld','6.3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8579,1,25,'Yld','6.8');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8580,1,26,'Yld','7.3');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8581,1,27,'Yld','7.5');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8582,1,28,'Yld','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8583,1,29,'Yld','5.4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8584,1,30,'Yld','5.9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8585,1,31,'Yld','6.4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8586,1,32,'Yld','6.9');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8587,1,33,'Yld','7.4');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8588,1,34,'Yld','7.6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8589,1,35,'Yld','7.7');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8590,1,36,'Yld','5.45');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8591,1,37,'Yld','5.95');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8592,1,38,'Yld','6.45');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8593,1,39,'Yld','na');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8594,1,40,'Yld','7.45');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8595,1,41,'Yld','7.65');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8596,1,42,'Yld','7.75');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8597,1,43,'Yld','5.6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8598,1,44,'Yld','6.1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8599,1,45,'Yld','6.6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8600,1,46,'Yld','7.1');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (8601,1,47,'Yld','7.6');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (11704,2,1,'GName','ALEX');
insert  into `studyrawdata`(`id`,`studyid`,`datarow`,`datacolumn`,`datavalue`) values (11705,2,1,'Yld','100');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
