package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.GermplasmReleaaseInfo;
import org.strasa.middleware.model.GermplasmReleaaseInfoExample;

public interface GermplasmReleaaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @SelectProvider(type=GermplasmReleaaseInfoSqlProvider.class, method="countByExample")
    int countByExample(GermplasmReleaaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @DeleteProvider(type=GermplasmReleaaseInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(GermplasmReleaaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @Delete({
        "delete from germplasmreleaseinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @Insert({
        "insert into germplasmreleaseinfo (germplasmname, attribute, ",
        "value)",
        "values (#{germplasmname,jdbcType=VARCHAR}, #{attribute,jdbcType=VARCHAR}, ",
        "#{value,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(GermplasmReleaaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @InsertProvider(type=GermplasmReleaaseInfoSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(GermplasmReleaaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @SelectProvider(type=GermplasmReleaaseInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="germplasmname", property="germplasmname", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribute", property="attribute", jdbcType=JdbcType.VARCHAR),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR)
    })
    List<GermplasmReleaaseInfo> selectByExample(GermplasmReleaaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @Select({
        "select",
        "id, germplasmname, attribute, value",
        "from germplasmreleaseinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="germplasmname", property="germplasmname", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribute", property="attribute", jdbcType=JdbcType.VARCHAR),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR)
    })
    GermplasmReleaaseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @UpdateProvider(type=GermplasmReleaaseInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GermplasmReleaaseInfo record, @Param("example") GermplasmReleaaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @UpdateProvider(type=GermplasmReleaaseInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GermplasmReleaaseInfo record, @Param("example") GermplasmReleaaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @UpdateProvider(type=GermplasmReleaaseInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GermplasmReleaaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table germplasmreleaseinfo
     *
     * @mbggenerated Wed Oct 09 14:07:54 SGT 2013
     */
    @Update({
        "update germplasmreleaseinfo",
        "set germplasmname = #{germplasmname,jdbcType=VARCHAR},",
          "attribute = #{attribute,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GermplasmReleaaseInfo record);
}