package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.Location;
import org.strasa.middleware.model.LocationExample;

public interface LocationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@SelectProvider(type = LocationSqlProvider.class, method = "countByExample")
	int countByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@DeleteProvider(type = LocationSqlProvider.class, method = "deleteByExample")
	int deleteByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@Delete({ "delete from location", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@Insert({
			"insert into location (ltype, nllp, ",
			"lname, labbr, snl3id, ",
			"snl2id, snl1id, ",
			"cntryid, lrplce, ",
			"nnpid)",
			"values (#{ltype,jdbcType=INTEGER}, #{nllp,jdbcType=INTEGER}, ",
			"#{lname,jdbcType=VARCHAR}, #{labbr,jdbcType=VARCHAR}, #{snl3id,jdbcType=INTEGER}, ",
			"#{snl2id,jdbcType=INTEGER}, #{snl1id,jdbcType=INTEGER}, ",
			"#{cntryid,jdbcType=INTEGER}, #{lrplce,jdbcType=INTEGER}, ",
			"#{nnpid,jdbcType=INTEGER})" })
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insert(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@InsertProvider(type = LocationSqlProvider.class, method = "insertSelective")
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insertSelective(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@SelectProvider(type = LocationSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ltype", property = "ltype", jdbcType = JdbcType.INTEGER),
			@Result(column = "nllp", property = "nllp", jdbcType = JdbcType.INTEGER),
			@Result(column = "lname", property = "lname", jdbcType = JdbcType.VARCHAR),
			@Result(column = "labbr", property = "labbr", jdbcType = JdbcType.VARCHAR),
			@Result(column = "snl3id", property = "snl3id", jdbcType = JdbcType.INTEGER),
			@Result(column = "snl2id", property = "snl2id", jdbcType = JdbcType.INTEGER),
			@Result(column = "snl1id", property = "snl1id", jdbcType = JdbcType.INTEGER),
			@Result(column = "cntryid", property = "cntryid", jdbcType = JdbcType.INTEGER),
			@Result(column = "lrplce", property = "lrplce", jdbcType = JdbcType.INTEGER),
			@Result(column = "nnpid", property = "nnpid", jdbcType = JdbcType.INTEGER) })
	List<Location> selectByExample(LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@Select({
			"select",
			"id, ltype, nllp, lname, labbr, snl3id, snl2id, snl1id, cntryid, lrplce, nnpid",
			"from location", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "ltype", property = "ltype", jdbcType = JdbcType.INTEGER),
			@Result(column = "nllp", property = "nllp", jdbcType = JdbcType.INTEGER),
			@Result(column = "lname", property = "lname", jdbcType = JdbcType.VARCHAR),
			@Result(column = "labbr", property = "labbr", jdbcType = JdbcType.VARCHAR),
			@Result(column = "snl3id", property = "snl3id", jdbcType = JdbcType.INTEGER),
			@Result(column = "snl2id", property = "snl2id", jdbcType = JdbcType.INTEGER),
			@Result(column = "snl1id", property = "snl1id", jdbcType = JdbcType.INTEGER),
			@Result(column = "cntryid", property = "cntryid", jdbcType = JdbcType.INTEGER),
			@Result(column = "lrplce", property = "lrplce", jdbcType = JdbcType.INTEGER),
			@Result(column = "nnpid", property = "nnpid", jdbcType = JdbcType.INTEGER) })
	Location selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@UpdateProvider(type = LocationSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Location record,
			@Param("example") LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@UpdateProvider(type = LocationSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Location record,
			@Param("example") LocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@UpdateProvider(type = LocationSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Location record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table location
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	@Update({ "update location", "set ltype = #{ltype,jdbcType=INTEGER},",
			"nllp = #{nllp,jdbcType=INTEGER},",
			"lname = #{lname,jdbcType=VARCHAR},",
			"labbr = #{labbr,jdbcType=VARCHAR},",
			"snl3id = #{snl3id,jdbcType=INTEGER},",
			"snl2id = #{snl2id,jdbcType=INTEGER},",
			"snl1id = #{snl1id,jdbcType=INTEGER},",
			"cntryid = #{cntryid,jdbcType=INTEGER},",
			"lrplce = #{lrplce,jdbcType=INTEGER},",
			"nnpid = #{nnpid,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Location record);
}