package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyVariable;
import org.strasa.middleware.model.StudyVariableExample;

public interface StudyVariableMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@SelectProvider(type = StudyVariableSqlProvider.class, method = "countByExample")
	int countByExample(StudyVariableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@DeleteProvider(type = StudyVariableSqlProvider.class, method = "deleteByExample")
	int deleteByExample(StudyVariableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@Delete({ "delete from studyvariable", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@Insert({
			"insert into studyvariable (traitcode, description, ",
			"methodid, scaleid, ",
			"applytofilter)",
			"values (#{traitcode,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
			"#{methodid,jdbcType=INTEGER}, #{scaleid,jdbcType=INTEGER}, ",
			"#{applytofilter,jdbcType=BIT})" })
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insert(StudyVariable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@InsertProvider(type = StudyVariableSqlProvider.class, method = "insertSelective")
	@Options(useGeneratedKeys = true, keyProperty = "id")
	int insertSelective(StudyVariable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@SelectProvider(type = StudyVariableSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "traitcode", property = "traitcode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR),
			@Result(column = "methodid", property = "methodid", jdbcType = JdbcType.INTEGER),
			@Result(column = "scaleid", property = "scaleid", jdbcType = JdbcType.INTEGER),
			@Result(column = "applytofilter", property = "applytofilter", jdbcType = JdbcType.BIT) })
	List<StudyVariable> selectByExample(StudyVariableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@Select({ "select",
			"id, traitcode, description, methodid, scaleid, applytofilter",
			"from studyvariable", "where id = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "traitcode", property = "traitcode", jdbcType = JdbcType.VARCHAR),
			@Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR),
			@Result(column = "methodid", property = "methodid", jdbcType = JdbcType.INTEGER),
			@Result(column = "scaleid", property = "scaleid", jdbcType = JdbcType.INTEGER),
			@Result(column = "applytofilter", property = "applytofilter", jdbcType = JdbcType.BIT) })
	StudyVariable selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@UpdateProvider(type = StudyVariableSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") StudyVariable record,
			@Param("example") StudyVariableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@UpdateProvider(type = StudyVariableSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") StudyVariable record,
			@Param("example") StudyVariableExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@UpdateProvider(type = StudyVariableSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(StudyVariable record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table studyvariable
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	@Update({ "update studyvariable",
			"set traitcode = #{traitcode,jdbcType=VARCHAR},",
			"description = #{description,jdbcType=VARCHAR},",
			"methodid = #{methodid,jdbcType=INTEGER},",
			"scaleid = #{scaleid,jdbcType=INTEGER},",
			"applytofilter = #{applytofilter,jdbcType=BIT}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(StudyVariable record);
}