package org.strasa.middleware.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.strasa.middleware.model.StudyGermplasmCharacteristic;
import org.strasa.middleware.model.StudyGermplasmCharacteristicExample;

public interface StudyGermplasmCharacteristicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @SelectProvider(type=StudyGermplasmCharacteristicSqlProvider.class, method="countByExample")
    int countByExample(StudyGermplasmCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @DeleteProvider(type=StudyGermplasmCharacteristicSqlProvider.class, method="deleteByExample")
    int deleteByExample(StudyGermplasmCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @Delete({
        "delete from studygermplasmcharacteristics",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @Insert({
        "insert into studygermplasmcharacteristics (id, studyid, ",
        "germplasmname, attribute, ",
        "value)",
        "values (#{id,jdbcType=INTEGER}, #{studyid,jdbcType=INTEGER}, ",
        "#{germplasmname,jdbcType=VARCHAR}, #{attribute,jdbcType=VARCHAR}, ",
        "#{value,jdbcType=VARCHAR})"
    })
    int insert(StudyGermplasmCharacteristic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @InsertProvider(type=StudyGermplasmCharacteristicSqlProvider.class, method="insertSelective")
    int insertSelective(StudyGermplasmCharacteristic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @SelectProvider(type=StudyGermplasmCharacteristicSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="studyid", property="studyid", jdbcType=JdbcType.INTEGER),
        @Result(column="germplasmname", property="germplasmname", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribute", property="attribute", jdbcType=JdbcType.VARCHAR),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR)
    })
    List<StudyGermplasmCharacteristic> selectByExample(StudyGermplasmCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @Select({
        "select",
        "id, studyid, germplasmname, attribute, value",
        "from studygermplasmcharacteristics",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="studyid", property="studyid", jdbcType=JdbcType.INTEGER),
        @Result(column="germplasmname", property="germplasmname", jdbcType=JdbcType.VARCHAR),
        @Result(column="attribute", property="attribute", jdbcType=JdbcType.VARCHAR),
        @Result(column="value", property="value", jdbcType=JdbcType.VARCHAR)
    })
    StudyGermplasmCharacteristic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @UpdateProvider(type=StudyGermplasmCharacteristicSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") StudyGermplasmCharacteristic record, @Param("example") StudyGermplasmCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @UpdateProvider(type=StudyGermplasmCharacteristicSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") StudyGermplasmCharacteristic record, @Param("example") StudyGermplasmCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @UpdateProvider(type=StudyGermplasmCharacteristicSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(StudyGermplasmCharacteristic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studygermplasmcharacteristics
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    @Update({
        "update studygermplasmcharacteristics",
        "set studyid = #{studyid,jdbcType=INTEGER},",
          "germplasmname = #{germplasmname,jdbcType=VARCHAR},",
          "attribute = #{attribute,jdbcType=VARCHAR},",
          "value = #{value,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(StudyGermplasmCharacteristic record);
}