package org.strasa.middleware.model;

public class Ecotype {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ecotype.id
	 * @mbggenerated  Wed Nov 27 10:48:14 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ecotype.ecotype
	 * @mbggenerated  Wed Nov 27 10:48:14 SGT 2013
	 */
	private String ecotype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ecotype.id
	 * @return  the value of ecotype.id
	 * @mbggenerated  Wed Nov 27 10:48:14 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ecotype.id
	 * @param id  the value for ecotype.id
	 * @mbggenerated  Wed Nov 27 10:48:14 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ecotype.ecotype
	 * @return  the value of ecotype.ecotype
	 * @mbggenerated  Wed Nov 27 10:48:14 SGT 2013
	 */
	public String getEcotype() {
		return ecotype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ecotype.ecotype
	 * @param ecotype  the value for ecotype.ecotype
	 * @mbggenerated  Wed Nov 27 10:48:14 SGT 2013
	 */
	public void setEcotype(String ecotype) {
		this.ecotype = ecotype;
	}
}