package org.strasa.middleware.model;

public class ExtensionData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.id
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.germplasmname
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private String germplasmname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.year
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private String year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.location
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.area
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private Double area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.datasource
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private String datasource;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.id
	 * @return  the value of extensiondata.id
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.id
	 * @param id  the value for extensiondata.id
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.germplasmname
	 * @return  the value of extensiondata.germplasmname
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public String getGermplasmname() {
		return germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.germplasmname
	 * @param germplasmname  the value for extensiondata.germplasmname
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setGermplasmname(String germplasmname) {
		this.germplasmname = germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.year
	 * @return  the value of extensiondata.year
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.year
	 * @param year  the value for extensiondata.year
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.location
	 * @return  the value of extensiondata.location
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.location
	 * @param location  the value for extensiondata.location
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.area
	 * @return  the value of extensiondata.area
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public Double getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.area
	 * @param area  the value for extensiondata.area
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setArea(Double area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.datasource
	 * @return  the value of extensiondata.datasource
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public String getDatasource() {
		return datasource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.datasource
	 * @param datasource  the value for extensiondata.datasource
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setDatasource(String datasource) {
		this.datasource = datasource;
	}
}