package org.strasa.middleware.model;

public class Germplasm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.id
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.gid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private Integer gid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.germplasmname
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String germplasmname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.othername
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String othername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.breeder
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String breeder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.germplasmtypeid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private Integer germplasmtypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.irnumber
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String irnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.ircross
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String ircross;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.parentage
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String parentage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.femaleparent
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String femaleparent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.maleparent
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String maleparent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.selectionhistory
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String selectionhistory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.source
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column germplasm.remarks
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.id
	 * @return  the value of germplasm.id
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.id
	 * @param id  the value for germplasm.id
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.gid
	 * @return  the value of germplasm.gid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public Integer getGid() {
		return gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.gid
	 * @param gid  the value for germplasm.gid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setGid(Integer gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.germplasmname
	 * @return  the value of germplasm.germplasmname
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getGermplasmname() {
		return germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.germplasmname
	 * @param germplasmname  the value for germplasm.germplasmname
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setGermplasmname(String germplasmname) {
		this.germplasmname = germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.othername
	 * @return  the value of germplasm.othername
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getOthername() {
		return othername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.othername
	 * @param othername  the value for germplasm.othername
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setOthername(String othername) {
		this.othername = othername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.breeder
	 * @return  the value of germplasm.breeder
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getBreeder() {
		return breeder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.breeder
	 * @param breeder  the value for germplasm.breeder
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setBreeder(String breeder) {
		this.breeder = breeder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.germplasmtypeid
	 * @return  the value of germplasm.germplasmtypeid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public Integer getGermplasmtypeid() {
		return germplasmtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.germplasmtypeid
	 * @param germplasmtypeid  the value for germplasm.germplasmtypeid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setGermplasmtypeid(Integer germplasmtypeid) {
		this.germplasmtypeid = germplasmtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.irnumber
	 * @return  the value of germplasm.irnumber
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getIrnumber() {
		return irnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.irnumber
	 * @param irnumber  the value for germplasm.irnumber
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setIrnumber(String irnumber) {
		this.irnumber = irnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.ircross
	 * @return  the value of germplasm.ircross
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getIrcross() {
		return ircross;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.ircross
	 * @param ircross  the value for germplasm.ircross
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setIrcross(String ircross) {
		this.ircross = ircross;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.parentage
	 * @return  the value of germplasm.parentage
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getParentage() {
		return parentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.parentage
	 * @param parentage  the value for germplasm.parentage
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setParentage(String parentage) {
		this.parentage = parentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.femaleparent
	 * @return  the value of germplasm.femaleparent
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getFemaleparent() {
		return femaleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.femaleparent
	 * @param femaleparent  the value for germplasm.femaleparent
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setFemaleparent(String femaleparent) {
		this.femaleparent = femaleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.maleparent
	 * @return  the value of germplasm.maleparent
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getMaleparent() {
		return maleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.maleparent
	 * @param maleparent  the value for germplasm.maleparent
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setMaleparent(String maleparent) {
		this.maleparent = maleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.selectionhistory
	 * @return  the value of germplasm.selectionhistory
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getSelectionhistory() {
		return selectionhistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.selectionhistory
	 * @param selectionhistory  the value for germplasm.selectionhistory
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setSelectionhistory(String selectionhistory) {
		this.selectionhistory = selectionhistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.source
	 * @return  the value of germplasm.source
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.source
	 * @param source  the value for germplasm.source
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column germplasm.remarks
	 * @return  the value of germplasm.remarks
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column germplasm.remarks
	 * @param remarks  the value for germplasm.remarks
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}