package org.strasa.middleware.model;

public class GermplasmCharacteristics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germplasmcharacteristics.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germplasmcharacteristics.germplasmname
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String germplasmname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germplasmcharacteristics.attribute
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column germplasmcharacteristics.value
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germplasmcharacteristics.id
     *
     * @return the value of germplasmcharacteristics.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germplasmcharacteristics.id
     *
     * @param id the value for germplasmcharacteristics.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germplasmcharacteristics.germplasmname
     *
     * @return the value of germplasmcharacteristics.germplasmname
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getGermplasmname() {
        return germplasmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germplasmcharacteristics.germplasmname
     *
     * @param germplasmname the value for germplasmcharacteristics.germplasmname
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setGermplasmname(String germplasmname) {
        this.germplasmname = germplasmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germplasmcharacteristics.attribute
     *
     * @return the value of germplasmcharacteristics.attribute
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germplasmcharacteristics.attribute
     *
     * @param attribute the value for germplasmcharacteristics.attribute
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column germplasmcharacteristics.value
     *
     * @return the value of germplasmcharacteristics.value
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column germplasmcharacteristics.value
     *
     * @param value the value for germplasmcharacteristics.value
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setValue(String value) {
        this.value = value;
    }
}