package org.strasa.middleware.model;

public class KeyGrainQuality {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keygrainquality.id
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keygrainquality.value
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keygrainquality.id
	 * @return  the value of keygrainquality.id
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keygrainquality.id
	 * @param id  the value for keygrainquality.id
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keygrainquality.value
	 * @return  the value of keygrainquality.value
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keygrainquality.value
	 * @param value  the value for keygrainquality.value
	 * @mbggenerated  Fri Nov 08 10:39:08 SGT 2013
	 */
	public void setValue(String value) {
		this.value = value;
	}
}