package org.strasa.middleware.model;

public class Location {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.ltype
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer ltype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.nllp
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer nllp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.lname
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private String lname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.labbr
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private String labbr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.snl3id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer snl3id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.snl2id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer snl2id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.snl1id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer snl1id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.cntryid
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer cntryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.lrplce
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer lrplce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.nnpid
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	private Integer nnpid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.id
	 * @return  the value of location.id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.id
	 * @param id  the value for location.id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.ltype
	 * @return  the value of location.ltype
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getLtype() {
		return ltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.ltype
	 * @param ltype  the value for location.ltype
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setLtype(Integer ltype) {
		this.ltype = ltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.nllp
	 * @return  the value of location.nllp
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getNllp() {
		return nllp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.nllp
	 * @param nllp  the value for location.nllp
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setNllp(Integer nllp) {
		this.nllp = nllp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.lname
	 * @return  the value of location.lname
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public String getLname() {
		return lname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.lname
	 * @param lname  the value for location.lname
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setLname(String lname) {
		this.lname = lname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.labbr
	 * @return  the value of location.labbr
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public String getLabbr() {
		return labbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.labbr
	 * @param labbr  the value for location.labbr
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setLabbr(String labbr) {
		this.labbr = labbr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.snl3id
	 * @return  the value of location.snl3id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getSnl3id() {
		return snl3id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.snl3id
	 * @param snl3id  the value for location.snl3id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setSnl3id(Integer snl3id) {
		this.snl3id = snl3id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.snl2id
	 * @return  the value of location.snl2id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getSnl2id() {
		return snl2id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.snl2id
	 * @param snl2id  the value for location.snl2id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setSnl2id(Integer snl2id) {
		this.snl2id = snl2id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.snl1id
	 * @return  the value of location.snl1id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getSnl1id() {
		return snl1id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.snl1id
	 * @param snl1id  the value for location.snl1id
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setSnl1id(Integer snl1id) {
		this.snl1id = snl1id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.cntryid
	 * @return  the value of location.cntryid
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getCntryid() {
		return cntryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.cntryid
	 * @param cntryid  the value for location.cntryid
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setCntryid(Integer cntryid) {
		this.cntryid = cntryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.lrplce
	 * @return  the value of location.lrplce
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getLrplce() {
		return lrplce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.lrplce
	 * @param lrplce  the value for location.lrplce
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setLrplce(Integer lrplce) {
		this.lrplce = lrplce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.nnpid
	 * @return  the value of location.nnpid
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public Integer getNnpid() {
		return nnpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.nnpid
	 * @param nnpid  the value for location.nnpid
	 * @mbggenerated  Thu Oct 17 13:40:28 SGT 2013
	 */
	public void setNnpid(Integer nnpid) {
		this.nnpid = nnpid;
	}
}