package org.strasa.middleware.model;

public class Program {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.userid
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.name
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.objective
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String objective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.coordinator
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String coordinator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.leadinginstitute
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String leadinginstitute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.collaborator
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String collaborator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.id
     *
     * @return the value of program.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.id
     *
     * @param id the value for program.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.userid
     *
     * @return the value of program.userid
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.userid
     *
     * @param userid the value for program.userid
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.name
     *
     * @return the value of program.name
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.name
     *
     * @param name the value for program.name
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.objective
     *
     * @return the value of program.objective
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getObjective() {
        return objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.objective
     *
     * @param objective the value for program.objective
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setObjective(String objective) {
        this.objective = objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.coordinator
     *
     * @return the value of program.coordinator
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getCoordinator() {
        return coordinator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.coordinator
     *
     * @param coordinator the value for program.coordinator
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setCoordinator(String coordinator) {
        this.coordinator = coordinator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.leadinginstitute
     *
     * @return the value of program.leadinginstitute
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getLeadinginstitute() {
        return leadinginstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.leadinginstitute
     *
     * @param leadinginstitute the value for program.leadinginstitute
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setLeadinginstitute(String leadinginstitute) {
        this.leadinginstitute = leadinginstitute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.collaborator
     *
     * @return the value of program.collaborator
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getCollaborator() {
        return collaborator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.collaborator
     *
     * @param collaborator the value for program.collaborator
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setCollaborator(String collaborator) {
        this.collaborator = collaborator;
    }
}