package org.strasa.middleware.model;

public class Project {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.id
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.userid
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.name
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.objective
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String objective;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.pi
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String pi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.leadinginstitute
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String leadinginstitute;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.collaborators
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String collaborators;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column project.fundingagency
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String fundingagency;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.id
	 * @return  the value of project.id
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.id
	 * @param id  the value for project.id
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.userid
	 * @return  the value of project.userid
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.userid
	 * @param userid  the value for project.userid
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.name
	 * @return  the value of project.name
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.name
	 * @param name  the value for project.name
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.objective
	 * @return  the value of project.objective
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getObjective() {
		return objective;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.objective
	 * @param objective  the value for project.objective
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setObjective(String objective) {
		this.objective = objective;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.pi
	 * @return  the value of project.pi
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getPi() {
		return pi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.pi
	 * @param pi  the value for project.pi
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setPi(String pi) {
		this.pi = pi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.leadinginstitute
	 * @return  the value of project.leadinginstitute
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getLeadinginstitute() {
		return leadinginstitute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.leadinginstitute
	 * @param leadinginstitute  the value for project.leadinginstitute
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setLeadinginstitute(String leadinginstitute) {
		this.leadinginstitute = leadinginstitute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.collaborators
	 * @return  the value of project.collaborators
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getCollaborators() {
		return collaborators;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.collaborators
	 * @param collaborators  the value for project.collaborators
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setCollaborators(String collaborators) {
		this.collaborators = collaborators;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column project.fundingagency
	 * @return  the value of project.fundingagency
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getFundingagency() {
		return fundingagency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column project.fundingagency
	 * @param fundingagency  the value for project.fundingagency
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setFundingagency(String fundingagency) {
		this.fundingagency = fundingagency;
	}
}