package org.strasa.middleware.model;

public class StudyVariable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.id
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.variablecode
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private String variablecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.description
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.property
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private String property;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.method
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private String method;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.scale
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private Integer scale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.applytofilter
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private String applytofilter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyvariable.defaultcolumn
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	private String defaultcolumn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.id
	 * @return  the value of studyvariable.id
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.id
	 * @param id  the value for studyvariable.id
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.variablecode
	 * @return  the value of studyvariable.variablecode
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public String getVariablecode() {
		return variablecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.variablecode
	 * @param variablecode  the value for studyvariable.variablecode
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setVariablecode(String variablecode) {
		this.variablecode = variablecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.description
	 * @return  the value of studyvariable.description
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.description
	 * @param description  the value for studyvariable.description
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.property
	 * @return  the value of studyvariable.property
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public String getProperty() {
		return property;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.property
	 * @param property  the value for studyvariable.property
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setProperty(String property) {
		this.property = property;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.method
	 * @return  the value of studyvariable.method
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public String getMethod() {
		return method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.method
	 * @param method  the value for studyvariable.method
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setMethod(String method) {
		this.method = method;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.scale
	 * @return  the value of studyvariable.scale
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public Integer getScale() {
		return scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.scale
	 * @param scale  the value for studyvariable.scale
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setScale(Integer scale) {
		this.scale = scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.applytofilter
	 * @return  the value of studyvariable.applytofilter
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public String getApplytofilter() {
		return applytofilter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.applytofilter
	 * @param applytofilter  the value for studyvariable.applytofilter
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setApplytofilter(String applytofilter) {
		this.applytofilter = applytofilter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyvariable.defaultcolumn
	 * @return  the value of studyvariable.defaultcolumn
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public String getDefaultcolumn() {
		return defaultcolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyvariable.defaultcolumn
	 * @param defaultcolumn  the value for studyvariable.defaultcolumn
	 * @mbggenerated  Thu Oct 10 13:49:48 SGT 2013
	 */
	public void setDefaultcolumn(String defaultcolumn) {
		this.defaultcolumn = defaultcolumn;
	}
}