package org.strasa.middleware.model;

public class StudyLocation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studylocation.id
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studylocation.studyid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studylocation.locationid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Integer locationid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studylocation.id
	 * @return  the value of studylocation.id
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studylocation.id
	 * @param id  the value for studylocation.id
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studylocation.studyid
	 * @return  the value of studylocation.studyid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studylocation.studyid
	 * @param studyid  the value for studylocation.studyid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studylocation.locationid
	 * @return  the value of studylocation.locationid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Integer getLocationid() {
		return locationid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studylocation.locationid
	 * @param locationid  the value for studylocation.locationid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setLocationid(Integer locationid) {
		this.locationid = locationid;
	}
}