package org.strasa.middleware.model;

public class StudyType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studytype.id
     *
     * @mbggenerated Fri Oct 25 13:11:54 SGT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studytype.studytype
     *
     * @mbggenerated Fri Oct 25 13:11:54 SGT 2013
     */
    private String studytype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studytype.id
     *
     * @return the value of studytype.id
     *
     * @mbggenerated Fri Oct 25 13:11:54 SGT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studytype.id
     *
     * @param id the value for studytype.id
     *
     * @mbggenerated Fri Oct 25 13:11:54 SGT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studytype.studytype
     *
     * @return the value of studytype.studytype
     *
     * @mbggenerated Fri Oct 25 13:11:54 SGT 2013
     */
    public String getStudytype() {
        return studytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studytype.studytype
     *
     * @param studytype the value for studytype.studytype
     *
     * @mbggenerated Fri Oct 25 13:11:54 SGT 2013
     */
    public void setStudytype(String studytype) {
        this.studytype = studytype;
    }
}