package org.strasa.middleware.model;

public class StudySite {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.id
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.studyid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.year
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.season
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String season;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.sitename
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String sitename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.sitelocation
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String sitelocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.ecotypeid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private Integer ecotypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.soiltype
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String soiltype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studysite.soilph
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	private String soilph;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.id
	 * @return  the value of studysite.id
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.id
	 * @param id  the value for studysite.id
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.studyid
	 * @return  the value of studysite.studyid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.studyid
	 * @param studyid  the value for studysite.studyid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.year
	 * @return  the value of studysite.year
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.year
	 * @param year  the value for studysite.year
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setYear(String year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.season
	 * @return  the value of studysite.season
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getSeason() {
		return season;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.season
	 * @param season  the value for studysite.season
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setSeason(String season) {
		this.season = season;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.sitename
	 * @return  the value of studysite.sitename
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getSitename() {
		return sitename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.sitename
	 * @param sitename  the value for studysite.sitename
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.sitelocation
	 * @return  the value of studysite.sitelocation
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getSitelocation() {
		return sitelocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.sitelocation
	 * @param sitelocation  the value for studysite.sitelocation
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setSitelocation(String sitelocation) {
		this.sitelocation = sitelocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.ecotypeid
	 * @return  the value of studysite.ecotypeid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public Integer getEcotypeid() {
		return ecotypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.ecotypeid
	 * @param ecotypeid  the value for studysite.ecotypeid
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setEcotypeid(Integer ecotypeid) {
		this.ecotypeid = ecotypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.soiltype
	 * @return  the value of studysite.soiltype
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getSoiltype() {
		return soiltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.soiltype
	 * @param soiltype  the value for studysite.soiltype
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setSoiltype(String soiltype) {
		this.soiltype = soiltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studysite.soilph
	 * @return  the value of studysite.soilph
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public String getSoilph() {
		return soilph;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studysite.soilph
	 * @param soilph  the value for studysite.soilph
	 * @mbggenerated  Mon Dec 02 10:45:06 SGT 2013
	 */
	public void setSoilph(String soilph) {
		this.soilph = soilph;
	}

	@Override
	public String toString() {
		return "StudySite [id=" + id + ", studyid=" + studyid + ", year="
				+ year + ", season=" + season + ", sitename=" + sitename
				+ ", sitelocation=" + sitelocation + ", ecotypeid=" + ecotypeid
				+ ", soiltype=" + soiltype + ", soilph=" + soilph + "]";
	}
}