package org.strasa.middleware.model;

public class StudyRawData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.id
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.studyid
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.datarow
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	private Integer datarow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.datacolumn
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	private String datacolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.datavalue
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	private String datavalue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.id
	 * @return  the value of studyrawdata.id
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.id
	 * @param id  the value for studyrawdata.id
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.studyid
	 * @return  the value of studyrawdata.studyid
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.studyid
	 * @param studyid  the value for studyrawdata.studyid
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.datarow
	 * @return  the value of studyrawdata.datarow
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public Integer getDatarow() {
		return datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.datarow
	 * @param datarow  the value for studyrawdata.datarow
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public void setDatarow(Integer datarow) {
		this.datarow = datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.datacolumn
	 * @return  the value of studyrawdata.datacolumn
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public String getDatacolumn() {
		return datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.datacolumn
	 * @param datacolumn  the value for studyrawdata.datacolumn
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public void setDatacolumn(String datacolumn) {
		this.datacolumn = datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.datavalue
	 * @return  the value of studyrawdata.datavalue
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public String getDatavalue() {
		return datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.datavalue
	 * @param datavalue  the value for studyrawdata.datavalue
	 * @mbggenerated  Tue Oct 29 15:37:45 SGT 2013
	 */
	public void setDatavalue(String datavalue) {
		this.datavalue = datavalue;
	}
}