package org.strasa.middleware.model;

public class StudyFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyfile.id
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyfile.userid
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyfile.studyid
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyfile.filename
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	private String filename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyfile.filepath
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	private String filepath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyfile.id
	 * @return  the value of studyfile.id
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyfile.id
	 * @param id  the value for studyfile.id
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyfile.userid
	 * @return  the value of studyfile.userid
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyfile.userid
	 * @param userid  the value for studyfile.userid
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyfile.studyid
	 * @return  the value of studyfile.studyid
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyfile.studyid
	 * @param studyid  the value for studyfile.studyid
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyfile.filename
	 * @return  the value of studyfile.filename
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyfile.filename
	 * @param filename  the value for studyfile.filename
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public void setFilename(String filename) {
		this.filename = filename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyfile.filepath
	 * @return  the value of studyfile.filepath
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public String getFilepath() {
		return filepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyfile.filepath
	 * @param filepath  the value for studyfile.filepath
	 * @mbggenerated  Wed Oct 09 14:15:37 SGT 2013
	 */
	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}
}