package org.strasa.middleware.model;

public class StudyDesign {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.id
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.studysiteid
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private Integer studysiteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.treatmentstructure
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private String treatmentstructure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.designstructure
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private String designstructure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.plotsize
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private String plotsize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.designfactor1
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private String designfactor1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.designfactor2
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private String designfactor2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.designfactor3
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private String designfactor3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.designfactor4
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	private String designfactor4;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.id
	 * @return  the value of studydesign.id
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.id
	 * @param id  the value for studydesign.id
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.studysiteid
	 * @return  the value of studydesign.studysiteid
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public Integer getStudysiteid() {
		return studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.studysiteid
	 * @param studysiteid  the value for studydesign.studysiteid
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setStudysiteid(Integer studysiteid) {
		this.studysiteid = studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.treatmentstructure
	 * @return  the value of studydesign.treatmentstructure
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public String getTreatmentstructure() {
		return treatmentstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.treatmentstructure
	 * @param treatmentstructure  the value for studydesign.treatmentstructure
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setTreatmentstructure(String treatmentstructure) {
		this.treatmentstructure = treatmentstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.designstructure
	 * @return  the value of studydesign.designstructure
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public String getDesignstructure() {
		return designstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.designstructure
	 * @param designstructure  the value for studydesign.designstructure
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setDesignstructure(String designstructure) {
		this.designstructure = designstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.plotsize
	 * @return  the value of studydesign.plotsize
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public String getPlotsize() {
		return plotsize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.plotsize
	 * @param plotsize  the value for studydesign.plotsize
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setPlotsize(String plotsize) {
		this.plotsize = plotsize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.designfactor1
	 * @return  the value of studydesign.designfactor1
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public String getDesignfactor1() {
		return designfactor1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.designfactor1
	 * @param designfactor1  the value for studydesign.designfactor1
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setDesignfactor1(String designfactor1) {
		this.designfactor1 = designfactor1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.designfactor2
	 * @return  the value of studydesign.designfactor2
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public String getDesignfactor2() {
		return designfactor2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.designfactor2
	 * @param designfactor2  the value for studydesign.designfactor2
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setDesignfactor2(String designfactor2) {
		this.designfactor2 = designfactor2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.designfactor3
	 * @return  the value of studydesign.designfactor3
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public String getDesignfactor3() {
		return designfactor3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.designfactor3
	 * @param designfactor3  the value for studydesign.designfactor3
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setDesignfactor3(String designfactor3) {
		this.designfactor3 = designfactor3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.designfactor4
	 * @return  the value of studydesign.designfactor4
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public String getDesignfactor4() {
		return designfactor4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.designfactor4
	 * @param designfactor4  the value for studydesign.designfactor4
	 * @mbggenerated  Wed Oct 30 16:54:42 SGT 2013
	 */
	public void setDesignfactor4(String designfactor4) {
		this.designfactor4 = designfactor4;
	}
}