package org.strasa.middleware.model;

import java.util.Date;

public class StudyAgronomy {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.id
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.studysiteid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Integer studysiteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.plantingtypeid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Integer plantingtypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.sowingdate
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Date sowingdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.harvestdate
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private Date harvestdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.fertilization
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private String fertilization;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyagronomy.density
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	private String density;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.id
	 * @return  the value of studyagronomy.id
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.id
	 * @param id  the value for studyagronomy.id
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.studysiteid
	 * @return  the value of studyagronomy.studysiteid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Integer getStudysiteid() {
		return studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.studysiteid
	 * @param studysiteid  the value for studyagronomy.studysiteid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setStudysiteid(Integer studysiteid) {
		this.studysiteid = studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.plantingtypeid
	 * @return  the value of studyagronomy.plantingtypeid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Integer getPlantingtypeid() {
		return plantingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.plantingtypeid
	 * @param plantingtypeid  the value for studyagronomy.plantingtypeid
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setPlantingtypeid(Integer plantingtypeid) {
		this.plantingtypeid = plantingtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.sowingdate
	 * @return  the value of studyagronomy.sowingdate
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Date getSowingdate() {
		return sowingdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.sowingdate
	 * @param sowingdate  the value for studyagronomy.sowingdate
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setSowingdate(Date sowingdate) {
		this.sowingdate = sowingdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.harvestdate
	 * @return  the value of studyagronomy.harvestdate
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public Date getHarvestdate() {
		return harvestdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.harvestdate
	 * @param harvestdate  the value for studyagronomy.harvestdate
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setHarvestdate(Date harvestdate) {
		this.harvestdate = harvestdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.fertilization
	 * @return  the value of studyagronomy.fertilization
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public String getFertilization() {
		return fertilization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.fertilization
	 * @param fertilization  the value for studyagronomy.fertilization
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setFertilization(String fertilization) {
		this.fertilization = fertilization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyagronomy.density
	 * @return  the value of studyagronomy.density
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public String getDensity() {
		return density;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyagronomy.density
	 * @param density  the value for studyagronomy.density
	 * @mbggenerated  Wed Nov 06 16:19:45 SGT 2013
	 */
	public void setDensity(String density) {
		this.density = density;
	}
}