package org.strasa.middleware.model;

public class StudyGermplasmCharacteristic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studygermplasmcharacteristics.id
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studygermplasmcharacteristics.studyid
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    private Integer studyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studygermplasmcharacteristics.germplasmname
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    private String germplasmname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studygermplasmcharacteristics.attribute
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studygermplasmcharacteristics.value
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studygermplasmcharacteristics.id
     *
     * @return the value of studygermplasmcharacteristics.id
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studygermplasmcharacteristics.id
     *
     * @param id the value for studygermplasmcharacteristics.id
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studygermplasmcharacteristics.studyid
     *
     * @return the value of studygermplasmcharacteristics.studyid
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public Integer getStudyid() {
        return studyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studygermplasmcharacteristics.studyid
     *
     * @param studyid the value for studygermplasmcharacteristics.studyid
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public void setStudyid(Integer studyid) {
        this.studyid = studyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studygermplasmcharacteristics.germplasmname
     *
     * @return the value of studygermplasmcharacteristics.germplasmname
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public String getGermplasmname() {
        return germplasmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studygermplasmcharacteristics.germplasmname
     *
     * @param germplasmname the value for studygermplasmcharacteristics.germplasmname
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public void setGermplasmname(String germplasmname) {
        this.germplasmname = germplasmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studygermplasmcharacteristics.attribute
     *
     * @return the value of studygermplasmcharacteristics.attribute
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studygermplasmcharacteristics.attribute
     *
     * @param attribute the value for studygermplasmcharacteristics.attribute
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studygermplasmcharacteristics.value
     *
     * @return the value of studygermplasmcharacteristics.value
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studygermplasmcharacteristics.value
     *
     * @param value the value for studygermplasmcharacteristics.value
     *
     * @mbggenerated Fri Oct 25 05:12:11 PHT 2013
     */
    public void setValue(String value) {
        this.value = value;
    }
}