package org.strasa.middleware.model;

public class StudyLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.studyid
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private Integer studyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.locationname
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String locationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.country
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.province
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.region
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.altitude
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String altitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.latitude
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studylocation.weatherstation
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    private String weatherstation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.id
     *
     * @return the value of studylocation.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.id
     *
     * @param id the value for studylocation.id
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.studyid
     *
     * @return the value of studylocation.studyid
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public Integer getStudyid() {
        return studyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.studyid
     *
     * @param studyid the value for studylocation.studyid
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setStudyid(Integer studyid) {
        this.studyid = studyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.locationname
     *
     * @return the value of studylocation.locationname
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getLocationname() {
        return locationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.locationname
     *
     * @param locationname the value for studylocation.locationname
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setLocationname(String locationname) {
        this.locationname = locationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.country
     *
     * @return the value of studylocation.country
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.country
     *
     * @param country the value for studylocation.country
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.province
     *
     * @return the value of studylocation.province
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.province
     *
     * @param province the value for studylocation.province
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.region
     *
     * @return the value of studylocation.region
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.region
     *
     * @param region the value for studylocation.region
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.altitude
     *
     * @return the value of studylocation.altitude
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getAltitude() {
        return altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.altitude
     *
     * @param altitude the value for studylocation.altitude
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setAltitude(String altitude) {
        this.altitude = altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.latitude
     *
     * @return the value of studylocation.latitude
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.latitude
     *
     * @param latitude the value for studylocation.latitude
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studylocation.weatherstation
     *
     * @return the value of studylocation.weatherstation
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public String getWeatherstation() {
        return weatherstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studylocation.weatherstation
     *
     * @param weatherstation the value for studylocation.weatherstation
     *
     * @mbggenerated Wed Oct 09 16:20:41 SGT 2013
     */
    public void setWeatherstation(String weatherstation) {
        this.weatherstation = weatherstation;
    }
}