package org.strasa.middleware.model;

public class StudyDesign {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.id
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.studysiteid
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private Integer studysiteid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.treatmentstructure
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String treatmentstructure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.designstructure
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String designstructure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studydesign.plotsize
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	private String plotsize;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.id
	 * @return  the value of studydesign.id
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.id
	 * @param id  the value for studydesign.id
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.studysiteid
	 * @return  the value of studydesign.studysiteid
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public Integer getStudysiteid() {
		return studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.studysiteid
	 * @param studysiteid  the value for studydesign.studysiteid
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setStudysiteid(Integer studysiteid) {
		this.studysiteid = studysiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.treatmentstructure
	 * @return  the value of studydesign.treatmentstructure
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getTreatmentstructure() {
		return treatmentstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.treatmentstructure
	 * @param treatmentstructure  the value for studydesign.treatmentstructure
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setTreatmentstructure(String treatmentstructure) {
		this.treatmentstructure = treatmentstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.designstructure
	 * @return  the value of studydesign.designstructure
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getDesignstructure() {
		return designstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.designstructure
	 * @param designstructure  the value for studydesign.designstructure
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setDesignstructure(String designstructure) {
		this.designstructure = designstructure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studydesign.plotsize
	 * @return  the value of studydesign.plotsize
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public String getPlotsize() {
		return plotsize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studydesign.plotsize
	 * @param plotsize  the value for studydesign.plotsize
	 * @mbggenerated  Wed Oct 09 14:15:35 SGT 2013
	 */
	public void setPlotsize(String plotsize) {
		this.plotsize = plotsize;
	}
}