package org.strasa.middleware.model;

public class StudyDerivedData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.id
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.studyid
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.dataset
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	private Integer dataset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.datarow
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	private Integer datarow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.datacolumn
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	private String datacolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.datavalue
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	private String datavalue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.id
	 * @return  the value of studyderiveddata.id
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.id
	 * @param id  the value for studyderiveddata.id
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.studyid
	 * @return  the value of studyderiveddata.studyid
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.studyid
	 * @param studyid  the value for studyderiveddata.studyid
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.dataset
	 * @return  the value of studyderiveddata.dataset
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public Integer getDataset() {
		return dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.dataset
	 * @param dataset  the value for studyderiveddata.dataset
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public void setDataset(Integer dataset) {
		this.dataset = dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.datarow
	 * @return  the value of studyderiveddata.datarow
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public Integer getDatarow() {
		return datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.datarow
	 * @param datarow  the value for studyderiveddata.datarow
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public void setDatarow(Integer datarow) {
		this.datarow = datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.datacolumn
	 * @return  the value of studyderiveddata.datacolumn
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public String getDatacolumn() {
		return datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.datacolumn
	 * @param datacolumn  the value for studyderiveddata.datacolumn
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public void setDatacolumn(String datacolumn) {
		this.datacolumn = datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.datavalue
	 * @return  the value of studyderiveddata.datavalue
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public String getDatavalue() {
		return datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.datavalue
	 * @param datavalue  the value for studyderiveddata.datavalue
	 * @mbggenerated  Fri Dec 13 11:10:23 SGT 2013
	 */
	public void setDatavalue(String datavalue) {
		this.datavalue = datavalue;
	}
}