package org.strasa.middleware.model;

public class StudyRawDataByDataColumn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.studyid
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.dataset
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	private Integer dataset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.datacolumn
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	private String datacolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyrawdata.datavalue
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	private String datavalue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.studyid
	 * @return  the value of studyrawdata.studyid
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.studyid
	 * @param studyid  the value for studyrawdata.studyid
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.dataset
	 * @return  the value of studyrawdata.dataset
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public Integer getDataset() {
		return dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.dataset
	 * @param dataset  the value for studyrawdata.dataset
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public void setDataset(Integer dataset) {
		this.dataset = dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.datacolumn
	 * @return  the value of studyrawdata.datacolumn
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public String getDatacolumn() {
		return datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.datacolumn
	 * @param datacolumn  the value for studyrawdata.datacolumn
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public void setDatacolumn(String datacolumn) {
		this.datacolumn = datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyrawdata.datavalue
	 * @return  the value of studyrawdata.datavalue
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public String getDatavalue() {
		return datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyrawdata.datavalue
	 * @param datavalue  the value for studyrawdata.datavalue
	 * @mbggenerated  Thu Jan 09 09:44:59 SGT 2014
	 */
	public void setDatavalue(String datavalue) {
		this.datavalue = datavalue;
	}
}