package org.strasa.middleware.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.lastname
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.firstname
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mi
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String mi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.agency
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String agency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.country
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	private String role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.lastname
	 * @return  the value of user.lastname
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.lastname
	 * @param lastname  the value for user.lastname
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.firstname
	 * @return  the value of user.firstname
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.firstname
	 * @param firstname  the value for user.firstname
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mi
	 * @return  the value of user.mi
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getMi() {
		return mi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mi
	 * @param mi  the value for user.mi
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setMi(String mi) {
		this.mi = mi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.agency
	 * @return  the value of user.agency
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getAgency() {
		return agency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.agency
	 * @param agency  the value for user.agency
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setAgency(String agency) {
		this.agency = agency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.country
	 * @return  the value of user.country
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.country
	 * @param country  the value for user.country
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role
	 * @return  the value of user.role
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role
	 * @param role  the value for user.role
	 * @mbggenerated  Fri Oct 18 13:25:23 SGT 2013
	 */
	public void setRole(String role) {
		this.role = role;
	}
}