package org.strasa.middleware.model;

public class Crosstype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosstype.id
     *
     * @mbggenerated Wed Oct 01 09:17:16 SGT 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crosstype.crosstype
     *
     * @mbggenerated Wed Oct 01 09:17:16 SGT 2014
     */
    private String crosstype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosstype.id
     *
     * @return the value of crosstype.id
     *
     * @mbggenerated Wed Oct 01 09:17:16 SGT 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosstype.id
     *
     * @param id the value for crosstype.id
     *
     * @mbggenerated Wed Oct 01 09:17:16 SGT 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crosstype.crosstype
     *
     * @return the value of crosstype.crosstype
     *
     * @mbggenerated Wed Oct 01 09:17:16 SGT 2014
     */
    public String getCrosstype() {
        return crosstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crosstype.crosstype
     *
     * @param crosstype the value for crosstype.crosstype
     *
     * @mbggenerated Wed Oct 01 09:17:16 SGT 2014
     */
    public void setCrosstype(String crosstype) {
        this.crosstype = crosstype;
    }
}