package org.strasa.middleware.model;

public class ExtensionData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.programid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer programid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.projectid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer projectid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.germplasmname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String germplasmname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.yearextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String yearextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.locationextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String locationextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.countryextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String countryextension;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.area
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Double area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.datasource
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String datasource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.yearrelease
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String yearrelease;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.countryrelease
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private String countryrelease;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.seedavailability
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer seedavailability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column extensiondata.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.id
	 * @return  the value of extensiondata.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.id
	 * @param id  the value for extensiondata.id
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.programid
	 * @return  the value of extensiondata.programid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getProgramid() {
		return programid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.programid
	 * @param programid  the value for extensiondata.programid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setProgramid(Integer programid) {
		this.programid = programid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.projectid
	 * @return  the value of extensiondata.projectid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getProjectid() {
		return projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.projectid
	 * @param projectid  the value for extensiondata.projectid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setProjectid(Integer projectid) {
		this.projectid = projectid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.germplasmname
	 * @return  the value of extensiondata.germplasmname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getGermplasmname() {
		return germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.germplasmname
	 * @param germplasmname  the value for extensiondata.germplasmname
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setGermplasmname(String germplasmname) {
		this.germplasmname = germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.yearextension
	 * @return  the value of extensiondata.yearextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getYearextension() {
		return yearextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.yearextension
	 * @param yearextension  the value for extensiondata.yearextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setYearextension(String yearextension) {
		this.yearextension = yearextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.locationextension
	 * @return  the value of extensiondata.locationextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getLocationextension() {
		return locationextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.locationextension
	 * @param locationextension  the value for extensiondata.locationextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setLocationextension(String locationextension) {
		this.locationextension = locationextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.countryextension
	 * @return  the value of extensiondata.countryextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getCountryextension() {
		return countryextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.countryextension
	 * @param countryextension  the value for extensiondata.countryextension
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setCountryextension(String countryextension) {
		this.countryextension = countryextension;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.area
	 * @return  the value of extensiondata.area
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Double getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.area
	 * @param area  the value for extensiondata.area
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setArea(Double area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.datasource
	 * @return  the value of extensiondata.datasource
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getDatasource() {
		return datasource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.datasource
	 * @param datasource  the value for extensiondata.datasource
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setDatasource(String datasource) {
		this.datasource = datasource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.yearrelease
	 * @return  the value of extensiondata.yearrelease
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getYearrelease() {
		return yearrelease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.yearrelease
	 * @param yearrelease  the value for extensiondata.yearrelease
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setYearrelease(String yearrelease) {
		this.yearrelease = yearrelease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.countryrelease
	 * @return  the value of extensiondata.countryrelease
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public String getCountryrelease() {
		return countryrelease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.countryrelease
	 * @param countryrelease  the value for extensiondata.countryrelease
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setCountryrelease(String countryrelease) {
		this.countryrelease = countryrelease;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.seedavailability
	 * @return  the value of extensiondata.seedavailability
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getSeedavailability() {
		return seedavailability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.seedavailability
	 * @param seedavailability  the value for extensiondata.seedavailability
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setSeedavailability(Integer seedavailability) {
		this.seedavailability = seedavailability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column extensiondata.userid
	 * @return  the value of extensiondata.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column extensiondata.userid
	 * @param userid  the value for extensiondata.userid
	 * @mbggenerated  Fri Feb 07 10:48:01 SGT 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}