package org.strasa.middleware.model;

public class KeyBiotic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keybiotic.id
	 * @mbggenerated  Wed Jan 29 14:14:00 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column keybiotic.value
	 * @mbggenerated  Wed Jan 29 14:14:00 SGT 2014
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keybiotic.id
	 * @return  the value of keybiotic.id
	 * @mbggenerated  Wed Jan 29 14:14:00 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keybiotic.id
	 * @param id  the value for keybiotic.id
	 * @mbggenerated  Wed Jan 29 14:14:00 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column keybiotic.value
	 * @return  the value of keybiotic.value
	 * @mbggenerated  Wed Jan 29 14:14:00 SGT 2014
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column keybiotic.value
	 * @param value  the value for keybiotic.value
	 * @mbggenerated  Wed Jan 29 14:14:00 SGT 2014
	 */
	public void setValue(String value) {
		this.value = value;
	}
}