package org.strasa.middleware.model;

public class StudyGermplasm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column studygermplasm.id
	 * 
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column studygermplasm.gref
	 * 
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	private Integer gref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column studygermplasm.studyid
	 * 
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column studygermplasm.dataset
	 * 
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	private Integer dataset;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column studygermplasm.id
	 * 
	 * @return the value of studygermplasm.id
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column studygermplasm.id
	 * 
	 * @param id
	 *            the value for studygermplasm.id
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column studygermplasm.gref
	 * 
	 * @return the value of studygermplasm.gref
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public Integer getGref() {
		return gref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column studygermplasm.gref
	 * 
	 * @param gref
	 *            the value for studygermplasm.gref
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public void setGref(Integer gref) {
		this.gref = gref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column studygermplasm.studyid
	 * 
	 * @return the value of studygermplasm.studyid
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column studygermplasm.studyid
	 * 
	 * @param studyid
	 *            the value for studygermplasm.studyid
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column studygermplasm.dataset
	 * 
	 * @return the value of studygermplasm.dataset
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public Integer getDataset() {
		return dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column studygermplasm.dataset
	 * 
	 * @param dataset
	 *            the value for studygermplasm.dataset
	 * @mbggenerated Mon Jan 27 09:45:38 SGT 2014
	 */
	public void setDataset(Integer dataset) {
		this.dataset = dataset;
	}

}