package org.strasa.middleware.model;

public class StudyGermplasm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.id
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.gref
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private Integer gref;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.studyid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.dataset
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private Integer dataset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.gid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private Integer gid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.germplasmname
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String germplasmname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.othername
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String othername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.breeder
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String breeder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.germplasmtypeid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private Integer germplasmtypeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.irnumber
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String irnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.ircross
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String ircross;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.parentage
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String parentage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.femaleparent
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String femaleparent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.maleparent
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String maleparent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.selectionhistory
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String selectionhistory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.source
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studygermplasm.remarks
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	private String remarks;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.id
	 * @return  the value of studygermplasm.id
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.id
	 * @param id  the value for studygermplasm.id
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.gref
	 * @return  the value of studygermplasm.gref
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public Integer getGref() {
		return gref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.gref
	 * @param gref  the value for studygermplasm.gref
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setGref(Integer gref) {
		this.gref = gref;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.studyid
	 * @return  the value of studygermplasm.studyid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.studyid
	 * @param studyid  the value for studygermplasm.studyid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.dataset
	 * @return  the value of studygermplasm.dataset
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public Integer getDataset() {
		return dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.dataset
	 * @param dataset  the value for studygermplasm.dataset
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setDataset(Integer dataset) {
		this.dataset = dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.gid
	 * @return  the value of studygermplasm.gid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public Integer getGid() {
		return gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.gid
	 * @param gid  the value for studygermplasm.gid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setGid(Integer gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.germplasmname
	 * @return  the value of studygermplasm.germplasmname
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getGermplasmname() {
		return germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.germplasmname
	 * @param germplasmname  the value for studygermplasm.germplasmname
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setGermplasmname(String germplasmname) {
		this.germplasmname = germplasmname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.othername
	 * @return  the value of studygermplasm.othername
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getOthername() {
		return othername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.othername
	 * @param othername  the value for studygermplasm.othername
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setOthername(String othername) {
		this.othername = othername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.breeder
	 * @return  the value of studygermplasm.breeder
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getBreeder() {
		return breeder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.breeder
	 * @param breeder  the value for studygermplasm.breeder
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setBreeder(String breeder) {
		this.breeder = breeder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.germplasmtypeid
	 * @return  the value of studygermplasm.germplasmtypeid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public Integer getGermplasmtypeid() {
		return germplasmtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.germplasmtypeid
	 * @param germplasmtypeid  the value for studygermplasm.germplasmtypeid
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setGermplasmtypeid(Integer germplasmtypeid) {
		this.germplasmtypeid = germplasmtypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.irnumber
	 * @return  the value of studygermplasm.irnumber
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getIrnumber() {
		return irnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.irnumber
	 * @param irnumber  the value for studygermplasm.irnumber
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setIrnumber(String irnumber) {
		this.irnumber = irnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.ircross
	 * @return  the value of studygermplasm.ircross
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getIrcross() {
		return ircross;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.ircross
	 * @param ircross  the value for studygermplasm.ircross
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setIrcross(String ircross) {
		this.ircross = ircross;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.parentage
	 * @return  the value of studygermplasm.parentage
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getParentage() {
		return parentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.parentage
	 * @param parentage  the value for studygermplasm.parentage
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setParentage(String parentage) {
		this.parentage = parentage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.femaleparent
	 * @return  the value of studygermplasm.femaleparent
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getFemaleparent() {
		return femaleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.femaleparent
	 * @param femaleparent  the value for studygermplasm.femaleparent
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setFemaleparent(String femaleparent) {
		this.femaleparent = femaleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.maleparent
	 * @return  the value of studygermplasm.maleparent
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getMaleparent() {
		return maleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.maleparent
	 * @param maleparent  the value for studygermplasm.maleparent
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setMaleparent(String maleparent) {
		this.maleparent = maleparent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.selectionhistory
	 * @return  the value of studygermplasm.selectionhistory
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getSelectionhistory() {
		return selectionhistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.selectionhistory
	 * @param selectionhistory  the value for studygermplasm.selectionhistory
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setSelectionhistory(String selectionhistory) {
		this.selectionhistory = selectionhistory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.source
	 * @return  the value of studygermplasm.source
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.source
	 * @param source  the value for studygermplasm.source
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studygermplasm.remarks
	 * @return  the value of studygermplasm.remarks
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studygermplasm.remarks
	 * @param remarks  the value for studygermplasm.remarks
	 * @mbggenerated  Tue Jan 21 14:04:49 SGT 2014
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Override
	public String toString() {
		return "StudyGermplasm [id=" + id + ", studyid=" + studyid + ", gid="
				+ gid + ", germplasmname=" + germplasmname + ", othername="
				+ othername + ", breeder=" + breeder + ", germplasmtypeid="
				+ germplasmtypeid + ", irnumber=" + irnumber + ", ircross="
				+ ircross + ", parentage=" + parentage + ", femaleparent="
				+ femaleparent + ", maleparent=" + maleparent
				+ ", selectionhistory=" + selectionhistory + ", source="
				+ source + ", remarks=" + remarks + "]";
	}
}