package org.strasa.middleware.model;

public class StudyDerivedData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.id
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.studyid
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private Integer studyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.dataset
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private Integer dataset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.datarow
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private Integer datarow;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.datacolumn
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private String datacolumn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.datavalue
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private String datavalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.shared
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private Boolean shared;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column studyderiveddata.userid
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.id
	 * @return  the value of studyderiveddata.id
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.id
	 * @param id  the value for studyderiveddata.id
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.studyid
	 * @return  the value of studyderiveddata.studyid
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public Integer getStudyid() {
		return studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.studyid
	 * @param studyid  the value for studyderiveddata.studyid
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setStudyid(Integer studyid) {
		this.studyid = studyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.dataset
	 * @return  the value of studyderiveddata.dataset
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public Integer getDataset() {
		return dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.dataset
	 * @param dataset  the value for studyderiveddata.dataset
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setDataset(Integer dataset) {
		this.dataset = dataset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.datarow
	 * @return  the value of studyderiveddata.datarow
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public Integer getDatarow() {
		return datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.datarow
	 * @param datarow  the value for studyderiveddata.datarow
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setDatarow(Integer datarow) {
		this.datarow = datarow;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.datacolumn
	 * @return  the value of studyderiveddata.datacolumn
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public String getDatacolumn() {
		return datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.datacolumn
	 * @param datacolumn  the value for studyderiveddata.datacolumn
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setDatacolumn(String datacolumn) {
		this.datacolumn = datacolumn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.datavalue
	 * @return  the value of studyderiveddata.datavalue
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public String getDatavalue() {
		return datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.datavalue
	 * @param datavalue  the value for studyderiveddata.datavalue
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setDatavalue(String datavalue) {
		this.datavalue = datavalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.shared
	 * @return  the value of studyderiveddata.shared
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public Boolean getShared() {
		return shared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.shared
	 * @param shared  the value for studyderiveddata.shared
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setShared(Boolean shared) {
		this.shared = shared;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column studyderiveddata.userid
	 * @return  the value of studyderiveddata.userid
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column studyderiveddata.userid
	 * @param userid  the value for studyderiveddata.userid
	 * @mbggenerated  Wed Jan 29 14:13:59 SGT 2014
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}