package org.strasa.middleware.model;

import java.util.Date;

public class UserValidation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uservalidation.id
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uservalidation.userID
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uservalidation.confirmationcode
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    private String confirmationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uservalidation.date_created
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    private Date dateCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uservalidation.id
     *
     * @return the value of uservalidation.id
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uservalidation.id
     *
     * @param id the value for uservalidation.id
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uservalidation.userID
     *
     * @return the value of uservalidation.userID
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uservalidation.userID
     *
     * @param userid the value for uservalidation.userID
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uservalidation.confirmationcode
     *
     * @return the value of uservalidation.confirmationcode
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public String getConfirmationcode() {
        return confirmationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uservalidation.confirmationcode
     *
     * @param confirmationcode the value for uservalidation.confirmationcode
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public void setConfirmationcode(String confirmationcode) {
        this.confirmationcode = confirmationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uservalidation.date_created
     *
     * @return the value of uservalidation.date_created
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uservalidation.date_created
     *
     * @param dateCreated the value for uservalidation.date_created
     *
     * @mbggenerated Thu Aug 07 13:30:16 SGT 2014
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
}